### ISSUE TITLE
Cannot delete default room 'main' from PySOGS.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/session-pysogs#97]
When trying to delete the `main` room, which is a carryover from the days of the Rust SOGS:

```
$ sudo sogs --delete-room main
2022-03-25 10:40:08,357 foo.com config[1333760] INFO Loading config from /etc/sogs/sogs.ini

main
====
Name: Main
Description: None
URL: http://foo.com/main?public_key=abcdec6c471ac0468c7c77e1cdc12f24a139ee8a07c6e3bf4e7855640dad821
Messages: 0 (0.0 MB)
Attachments: 0 (0.0 MB)
Active users: 2 (7d), 2 (14d) 2 (30d)
Moderators: 0 admins (0 hidden), 0 moderators (0 hidden)
Are you sure you want to delete this room? [yN] y
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/sogs/__main__.py", line 169, in <module>
    cur.execute("DELETE FROM rooms WHERE token = ?", [args.delete_room])
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by jagerman** [comment]
I thought I'd fixed that in `dev` but apparently not.
